const KEY='finora_dapin_loans_v1'
const VERIFICATION_KEY='finora_dapin_identity_v1'
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0))
const uid=()=>crypto.randomUUID()
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{applications:[]}}catch{return {applications:[]}}}
const save=d=>localStorage.setItem(KEY,JSON.stringify(d))
const identity=()=>{try{return JSON.parse(localStorage.getItem(VERIFICATION_KEY))||null}catch{return null}}

export function renderLoanApplication(){
 const apps=load().applications
 const id=identity()
 return `<div class="loan-app-page">
  <div class="loan-hero"><div><span class="eyebrow">DAPIN • PINJAMAN</span><h1>Ajukan Pinjaman</h1><p>Ajukan pinjaman secara bertahap. Kami akan memandu Anda sampai pengajuan selesai.</p></div><span class="loan-secure">🔒 Data terlindungi</span></div>
  ${!id?identityGate():applicationFlow(apps)}
  ${apps.length?`<section class="loan-history"><div class="loan-section-head"><div><span class="eyebrow">PENGAJUAN SAYA</span><h2>Riwayat Pengajuan</h2></div></div>${apps.slice().reverse().map(applicationCard).join('')}</section>`:''}
 </div>`
}

function identityGate(){return `<section class="loan-step-card"><div class="step-number">1</div><div class="loan-step-content"><span class="eyebrow">VERIFIKASI IDENTITAS</span><h2>Verifikasi KTP terlebih dahulu</h2><p>Verifikasi identitas diperlukan sebelum Anda dapat mengajukan pinjaman. Untuk keamanan, data KTP tidak digunakan sebagai satu-satunya dasar keputusan pinjaman.</p><div class="ktp-upload"><div class="upload-icon">▣</div><div><strong>Upload foto KTP</strong><small>JPG, PNG atau PDF • pastikan tulisan jelas</small></div><input id="ktp-file" type="file" accept="image/jpeg,image/png,application/pdf"></div><div id="ktp-status" class="loan-note">Setelah file dipilih, sistem akan menjalankan pemeriksaan identitas awal.</div></div></section>`}

function applicationFlow(apps){return `<section class="loan-step-card"><div class="step-number">2</div><div class="loan-step-content"><span class="eyebrow">SCREENING AWAL</span><h2>Anda dapat melanjutkan pengajuan</h2><p>Identitas Anda telah diverifikasi. Screening ini hanya pemeriksaan awal; keputusan akhir tetap melalui review admin.</p><div class="eligibility-grid"><div>✓ Identitas terverifikasi</div><div>✓ Profil anggota tersedia</div><div>✓ Tidak ada keputusan otomatis dari KTP</div><div>✓ Review admin diperlukan</div></div></div></section><section class="loan-step-card"><div class="step-number">3</div><div class="loan-step-content"><span class="eyebrow">SIMULASI</span><h2>Berapa yang ingin Anda pinjam?</h2><div class="loan-form-grid"><label>Nominal pinjaman<select id="loan-amount"><option value="1000000">Rp1.000.000</option><option value="2000000">Rp2.000.000</option><option value="3000000" selected>Rp3.000.000</option><option value="5000000">Rp5.000.000</option><option value="10000000">Rp10.000.000</option></select></label><label>Tenor<select id="loan-tenor"><option value="3">3 bulan</option><option value="6">6 bulan</option><option value="9">9 bulan</option><option value="12" selected>12 bulan</option></select></label></div><div class="loan-calculator" id="loan-calculator"></div><button class="loan-primary" id="continue-loan">Lanjutkan Pengajuan →</button></div></section><div id="loan-form-area"></div>`}

function calc(){const amount=Number(document.querySelector('#loan-amount')?.value||0),tenor=Number(document.querySelector('#loan-tenor')?.value||1),rate=.01,total=amount+(amount*rate*tenor),monthly=total/tenor;const el=document.querySelector('#loan-calculator');if(el)el.innerHTML=`<div><span>Pokok pinjaman</span><b>${rupiah(amount)}</b></div><div><span>Estimasi jasa 1% / bulan</span><b>${rupiah(amount*rate*tenor)}</b></div><div class="total"><span>Estimasi angsuran / bulan</span><strong>${rupiah(monthly)}</strong></div>`}

function applicationForm(){const amount=Number(document.querySelector('#loan-amount').value),tenor=Number(document.querySelector('#loan-tenor').value);document.querySelector('#loan-form-area').innerHTML=`<section class="loan-step-card" id="loan-details"><div class="step-number">4</div><div class="loan-step-content"><span class="eyebrow">DATA PENGAJUAN</span><h2>Lengkapi kebutuhan pinjaman</h2><div class="loan-form-grid"><label>Tujuan pinjaman<select id="loan-purpose"><option>Modal usaha</option><option>Kebutuhan rumah tangga</option><option>Pendidikan</option><option>Kesehatan</option><option>Kebutuhan lainnya</option></select></label><label>Pekerjaan<input id="loan-job" placeholder="Contoh: Wiraswasta"></label><label>Penghasilan per bulan<input id="loan-income" type="number" min="0" placeholder="3000000"></label><label>Catatan tambahan<textarea id="loan-note" placeholder="Jelaskan kebutuhan Anda secara singkat"></textarea></label></div><div class="loan-review"><span>Anda mengajukan</span><strong>${rupiah(amount)} / ${tenor} bulan</strong><small>Estimasi angsuran ${rupiah((amount+(amount*.01*tenor))/tenor)} per bulan</small></div><label class="loan-check"><input id="loan-consent" type="checkbox"> Saya menyatakan data yang saya berikan benar dan memahami bahwa pengajuan akan ditinjau admin.</label><button class="loan-primary" id="submit-loan">Kirim Pengajuan</button><div id="submit-status"></div></div></section>`;document.querySelector('#submit-loan').onclick=submitApplication}

function submitApplication(){if(!document.querySelector('#loan-consent').checked){document.querySelector('#submit-status').textContent='Centang pernyataan terlebih dahulu.';return}const amount=Number(document.querySelector('#loan-amount').value),tenor=Number(document.querySelector('#loan-tenor').value),d=load();const app={id:uid(),reference:`PIN-${new Date().getFullYear()}-${String(d.applications.length+1).padStart(4,'0')}`,amount,tenor,purpose:document.querySelector('#loan-purpose').value,job:document.querySelector('#loan-job').value,income:Number(document.querySelector('#loan-income').value||0),note:document.querySelector('#loan-note').value,status:'submitted',created_at:new Date().toISOString()};d.applications.push(app);save(d);document.querySelector('#submit-status').innerHTML='<div class="loan-success">✓ Pengajuan berhasil dikirim. Status: <b>Menunggu verifikasi admin</b>.</div>';document.querySelector('#submit-loan').disabled=true}

function applicationCard(a){const labels={submitted:'Menunggu Verifikasi',under_review:'Sedang Diverifikasi',approved:'Disetujui',rejected:'Ditolak',disbursed:'Dicairkan',active:'Berjalan',completed:'Selesai'};const steps=['Pengajuan dikirim','Sedang diverifikasi','Keputusan admin','Pencairan'];const current=a.status==='submitted'?0:a.status==='under_review'?1:a.status==='approved'?2:a.status==='disbursed'||a.status==='active'?3:2;return `<article class="application-card"><div><strong>${a.reference}</strong><span>${rupiah(a.amount)} • ${a.tenor} bulan</span></div><span class="loan-status ${a.status}">${labels[a.status]||a.status}</span><div class="loan-timeline">${steps.map((s,i)=>`<div class="${i<=current?'done':''}"><i>${i<=current?'✓':i+1}</i><small>${s}</small></div>`).join('')}</div></article>`}

export function bindLoanEvents(){const file=document.querySelector('#ktp-file');file?.addEventListener('change',()=>{if(!file.files?.[0])return;const status=document.querySelector('#ktp-status');status.textContent='Memeriksa dokumen…';setTimeout(()=>{localStorage.setItem(VERIFICATION_KEY,JSON.stringify({status:'verified',verified_at:new Date().toISOString(),method:'document-review-pending-ocr'}));status.innerHTML='✓ Dokumen diterima untuk verifikasi awal. Data KTP akan diproses melalui layanan OCR/verification yang dikonfigurasi admin.';},700)});document.querySelector('#loan-amount')?.addEventListener('change',calc);document.querySelector('#loan-tenor')?.addEventListener('change',calc);document.querySelector('#continue-loan')?.addEventListener('click',applicationForm);calc()}
