const KEY='finora_dapin_v2'
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0))
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
const total=a=>(a||[]).reduce((s,x)=>s+Number(x.amount||0),0)
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))
const style=document.createElement('style')
style.textContent=`
.dapin-report-dashboard{margin-top:18px;background:#0b111b;border:1px solid #202c3d;border-radius:20px;padding:20px}.dr-head{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin-bottom:18px}.dr-head span{font-size:9px;letter-spacing:.16em;color:#f472b6;font-weight:800}.dr-head h2{margin:5px 0;font-size:22px}.dr-head p{margin:0;color:#7d899c;font-size:11px}.dr-badge{border:1px solid #2a3850;background:#111a27;border-radius:10px;padding:9px 11px;color:#9eabbd;font-size:9px}.dr-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.dr-card{background:#0f1722;border:1px solid #253247;border-radius:16px;padding:16px}.dr-card.wide{grid-column:1/-1}.dr-card h3{margin:5px 0 12px;font-size:15px}.dr-card small{display:block;color:#6f7c90;font-size:8px;letter-spacing:.14em}.dr-row{display:grid;grid-template-columns:125px 1fr 120px;align-items:center;gap:10px;font-size:10px;margin:10px 0}.dr-row>span{color:#a3adbb}.dr-row>b{text-align:right;color:#eef1f5}.dr-track{height:10px;background:#172235;border-radius:99px;overflow:hidden}.dr-track i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#8b6cff,#4ea1ff)}.dr-donut{width:150px;height:150px;border-radius:50%;margin:8px auto 14px;background:conic-gradient(#8b6cff 0 33%,#4ea1ff 33% 66%,#55ddb0 66% 100%);position:relative}.dr-donut:after{content:"";position:absolute;inset:24px;background:#0f1722;border-radius:50%}.dr-legend{display:grid;gap:7px}.dr-legend div{display:flex;justify-content:space-between;gap:10px;font-size:10px}.dr-legend span{color:#8d99ab}.dr-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.dr-kpi{background:#101926;border:1px solid #243249;border-radius:13px;padding:13px}.dr-kpi span{display:block;color:#6f7c90;font-size:8px}.dr-kpi strong{display:block;font-size:17px;margin-top:7px}.dr-kpi small{display:block;color:#69768a;font-size:8px;margin-top:4px}@media(max-width:900px){.dr-grid{grid-template-columns:1fr}.dr-card.wide{grid-column:auto}.dr-kpis{grid-template-columns:1fr 1fr}.dr-row{grid-template-columns:100px 1fr 90px}}
`
document.head.appendChild(style)
const active=()=>document.querySelector('.dapin-nav[data-dapin-view="laporan"].active')
const getRoot=()=>document.querySelector('.dapin-admin-panel .dapin-main')
const isReport=()=>{const r=getRoot();const h=r?.querySelector('.dapin-page-head h1')?.textContent?.trim();return !!r&&!!active()&&(h==='Laporan'||h==='Laporan Keuangan'||h==='Dashboard Laporan')}
const bar=(label,value,max,moneyVal=true)=>`<div class="dr-row"><span>${esc(label)}</span><div class="dr-track"><i style="width:${Math.max(3,Math.min(100,(Number(value||0)/Math.max(max,1))*100))}%"></i></div><b>${moneyVal?money(value):Number(value||0).toLocaleString('id-ID')}</b></div>`
const render=()=>{
 const root=getRoot()
 if(!root||!isReport()){root?.querySelector('[data-dapin-report-dashboard]')?.remove();return}
 const old=root.querySelector('[data-dapin-report-dashboard]');if(old)old.remove()
 const d=read(),members=d.members||[],savings=d.savings||[],loans=d.loans||[],payments=d.payments||[],transactions=d.transactions||[]
 const totalSavings=total(savings),totalLoans=total(loans),totalPayments=total(payments)
 const outstanding=loans.reduce((s,x)=>s+Math.max(0,Number(x.amount||0)-Number(x.paid||0)),0)
 const activeLoans=loans.filter(x=>Number(x.amount||0)>Number(x.paid||0)).length
 const paidLoans=loans.filter(x=>Number(x.amount||0)<=Number(x.paid||0)).length
 const txIn=transactions.filter(x=>x.direction!=='out').reduce((s,x)=>s+Number(x.amount||0),0)
 const txOut=transactions.filter(x=>x.direction==='out').reduce((s,x)=>s+Number(x.amount||0),0)
 const masuk=totalSavings+totalPayments,keluar=totalLoans,net=masuk-keluar
 const pokok=total(savings.filter(x=>x.type==='Simpanan Pokok')),wajib=total(savings.filter(x=>x.type==='Simpanan Wajib')),sukarela=total(savings.filter(x=>x.type==='Simpanan Sukarela'))
 const maxFlow=Math.max(masuk,keluar,Math.max(net,0),1),maxLoans=Math.max(activeLoans,paidLoans,1)
 const el=document.createElement('section');el.className='dapin-report-dashboard';el.dataset.dapinReportDashboard='1'
 el.innerHTML=`<div class="dr-head"><div><span>LIVE ANALYTICS</span><h2>Grafik Operasional DAPIN</h2><p>Grafik otomatis mengikuti data DAPIN yang tersimpan.</p></div><div class="dr-badge">AUTO • ${new Date().toLocaleString('id-ID')}</div></div><div class="dr-kpis"><div class="dr-kpi"><span>ANGGOTA</span><strong>${members.length}</strong><small>data master</small></div><div class="dr-kpi"><span>SIMPANAN</span><strong>${money(totalSavings)}</strong><small>total simpanan</small></div><div class="dr-kpi"><span>OUTSTANDING</span><strong>${money(outstanding)}</strong><small>pinjaman berjalan</small></div><div class="dr-kpi"><span>ANGSURAN</span><strong>${money(totalPayments)}</strong><small>total terkumpul</small></div></div><div class="dr-grid"><article class="dr-card wide"><small>ARUS KEUANGAN</small><h3>Masuk • Keluar • Net</h3>${bar('Total masuk',masuk,maxFlow,true)}${bar('Total pinjaman',keluar,maxFlow,true)}${bar('Net operasional',Math.max(net,0),maxFlow,true)}</article><article class="dr-card"><small>SIMPANAN</small><h3>Komposisi Simpanan</h3><div class="dr-donut"></div><div class="dr-legend"><div><span>Pokok</span><b>${money(pokok)}</b></div><div><span>Wajib</span><b>${money(wajib)}</b></div><div><span>Sukarela</span><b>${money(sukarela)}</b></div></div></article><article class="dr-card"><small>PINJAMAN</small><h3>Status Kredit</h3>${bar('Berjalan',activeLoans,maxLoans,false)}${bar('Lunas',paidLoans,maxLoans,false)}${bar('Outstanding',outstanding,Math.max(outstanding,totalLoans,1),true)}</article><article class="dr-card"><small>ANGSURAN</small><h3>Pembayaran Terkumpul</h3>${bar('Angsuran masuk',totalPayments,Math.max(totalPayments,1),true)}<div class="dr-legend"><div><span>Total pembayaran</span><b>${money(totalPayments)}</b></div><div><span>Jumlah catatan</span><b>${payments.length.toLocaleString('id-ID')}</b></div></div></article><article class="dr-card"><small>TRANSAKSI</small><h3>Kas Masuk vs Keluar</h3>${bar('Masuk',txIn,Math.max(txIn,txOut,1),true)}${bar('Keluar',txOut,Math.max(txIn,txOut,1),true)}<div class="dr-legend"><div><span>Net transaksi</span><b>${money(txIn-txOut)}</b></div></div></article><article class="dr-card"><small>ANGGOTA</small><h3>Aktivitas Keanggotaan</h3>${bar('Total anggota',members.length,Math.max(members.length,1),false)}${bar('Dengan pinjaman',new Set(loans.filter(x=>Number(x.amount||0)>Number(x.paid||0)).map(x=>x.member_id)).size,Math.max(members.length,1),false)}<div class="dr-legend"><div><span>Anggota terdaftar</span><b>${members.length}</b></div><div><span>Pinjaman berjalan</span><b>${activeLoans}</b></div></div></article></div>`
 root.appendChild(el)
}
render()
new MutationObserver(render).observe(document.documentElement,{childList:true,subtree:true})
setInterval(render,1200)
window.addEventListener('storage',render)
