const KEY='finora_dapin_v1'
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0))
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const uid=()=>crypto.randomUUID()
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{members:[],savings:[],loans:[],payments:[],view:'dashboard'}}catch{return {members:[],savings:[],loans:[],payments:[],view:'dashboard'}}}
const save=d=>localStorage.setItem(KEY,JSON.stringify(d))
let db=load()
const totalSavings=()=>db.savings.reduce((a,x)=>a+Number(x.amount||0),0)
const activeLoans=()=>db.loans.filter(x=>x.status!=='paid')
const outstanding=()=>activeLoans().reduce((a,x)=>a+Math.max(0,Number(x.amount||0)-Number(x.paid||0)),0)

export function renderDapin(){
 const v=db.view||'dashboard'
 const pages={dashboard:dashboard,anggota:members,simpanan:savings,pinjaman:loans,angsuran:payments,transaksi:transactions,laporan:reports}
 return `<section class="dapin-app"><aside class="dapin-sidebar"><div class="dapin-brand"><span>D</span><div><strong>DAPIN</strong><small>Balongbendo</small></div></div><div class="dapin-menu">${[['dashboard','⌂','Dashboard'],['anggota','♙','Anggota'],['simpanan','◈','Simpanan'],['pinjaman','▣','Pinjaman'],['angsuran','◷','Angsuran'],['transaksi','↔','Transaksi'],['laporan','▥','Laporan']].map(([id,i,l])=>`<button class="dapin-nav ${v===id?'active':''}" data-dapin-view="${id}"><b>${i}</b><span>${l}</span></button>`).join('')}</div><div class="dapin-side-foot"><span class="dapin-live">● FINORA SESSION</span><small>Terhubung & aman</small></div></aside><div class="dapin-main"><div class="dapin-mobile-head"><button data-dapin-toggle>☰</button><strong>DAPIN</strong></div>${pages[v]?pages[v]():dashboard()}</div></section>`
}

function header(kicker,title,desc,action=''){return `<div class="dapin-page-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div>${action}</div>`}
function dashboard(){return `${header('DAPIN BALONGBENDO','Dashboard','Ringkasan operasional simpan pinjam dan aktivitas koperasi.','<button class="dapin-primary" data-dapin-action="add-member">＋ Anggota Baru</button>')}<div class="dapin-kpis"><article><span>Total Anggota</span><strong>${db.members.length}</strong><small>Data terdaftar</small></article><article><span>Total Simpanan</span><strong>${rupiah(totalSavings())}</strong><small>Seluruh simpanan</small></article><article><span>Piutang Berjalan</span><strong>${rupiah(outstanding())}</strong><small>${activeLoans().length} pinjaman aktif</small></article><article><span>Angsuran Masuk</span><strong>${rupiah(db.payments.reduce((a,x)=>a+Number(x.amount||0),0))}</strong><small>Total tercatat</small></article></div><div class="dapin-columns"><section class="dapin-panel"><div class="dapin-panel-head"><div><span>OPERASIONAL</span><h2>Modul utama</h2></div></div><div class="dapin-modules">${[['anggota','♙','Anggota','Kelola data anggota'],['simpanan','◈','Simpanan','Catat simpanan anggota'],['pinjaman','▣','Pinjaman','Pengajuan & pencairan'],['angsuran','◷','Angsuran','Pembayaran cicilan'],['transaksi','↔','Transaksi','Buku transaksi'],['laporan','▥','Laporan','Ringkasan keuangan']].map(([id,i,t,d])=>`<button data-dapin-view="${id}"><b>${i}</b><span><strong>${t}</strong><small>${d}</small></span><em>›</em></button>`).join('')}</div></section><section class="dapin-panel"><div class="dapin-panel-head"><div><span>STATUS</span><h2>Aktivitas terbaru</h2></div></div>${recent()}</section></div>`}
function recent(){const rows=[...db.payments.map(x=>({...x,label:'Pembayaran angsuran',sign:'+',cls:'in'})),...db.savings.map(x=>({...x,label:'Simpanan anggota',sign:'+',cls:'in'})),...db.loans.map(x=>({...x,label:'Pencairan pinjaman',sign:'-',cls:'out'}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,6);if(!rows.length)return '<div class="dapin-empty">Belum ada aktivitas. Gunakan modul di sebelah kiri untuk mulai mencatat data.</div>';return `<div class="dapin-list">${rows.map(x=>`<div><span><strong>${esc(x.label)}</strong><small>${esc(x.member_name||'Anggota')} • ${new Date(x.created_at).toLocaleString('id-ID')}</small></span><b class="${x.cls}">${x.sign}${rupiah(x.amount)}</b></div>`).join('')}</div>`}
function members(){return `${header('DATA MASTER','Anggota','Kelola identitas, status, dan nomor anggota.','<button class="dapin-primary" data-dapin-action="add-member">＋ Tambah Anggota</button>')}<section class="dapin-panel"><div class="dapin-toolbar"><input data-dapin-search="members" placeholder="Cari nama / nomor anggota…"><span>${db.members.length} anggota</span></div><div class="dapin-table-wrap"><table><thead><tr><th>No. Anggota</th><th>Nama</th><th>No. HP</th><th>Status</th><th>Terdaftar</th><th></th></tr></thead><tbody>${db.members.length?db.members.map(m=>`<tr><td><b>${esc(m.code)}</b></td><td>${esc(m.name)}</td><td>${esc(m.phone||'-')}</td><td><span class="status active">Aktif</span></td><td>${esc(m.joined||'-')}</td><td><button class="table-action" data-dapin-action="delete-member" data-id="${m.id}">Hapus</button></td></tr>`).join(''):'<tr><td colspan="6" class="table-empty">Belum ada anggota.</td></tr>'}</tbody></table></div></section>`}
function savings(){return `${header('KEUANGAN','Simpanan','Catat simpanan pokok, wajib, dan sukarela anggota.','<button class="dapin-primary" data-dapin-action="add-saving">＋ Catat Simpanan</button>')}<div class="dapin-kpis compact"><article><span>Total</span><strong>${rupiah(totalSavings())}</strong></article><article><span>Transaksi</span><strong>${db.savings.length}</strong></article><article><span>Rata-rata</span><strong>${rupiah(db.savings.length?totalSavings()/db.savings.length:0)}</strong></article></div><section class="dapin-panel"><div class="dapin-table-wrap"><table><thead><tr><th>Tanggal</th><th>Anggota</th><th>Jenis</th><th>Nominal</th><th>Keterangan</th></tr></thead><tbody>${db.savings.length?db.savings.slice().reverse().map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString('id-ID')}</td><td>${esc(x.member_name)}</td><td>${esc(x.type)}</td><td class="money-in">+${rupiah(x.amount)}</td><td>${esc(x.note||'-')}</td></tr>`).join(''):'<tr><td colspan="5" class="table-empty">Belum ada simpanan tercatat.</td></tr>'}</tbody></table></div></section>`}
function loans(){return `${header('KREDIT','Pinjaman','Kelola pengajuan, pencairan, tenor, dan saldo pinjaman.','<button class="dapin-primary" data-dapin-action="add-loan">＋ Pinjaman Baru</button>')}<section class="dapin-panel"><div class="dapin-table-wrap"><table><thead><tr><th>Anggota</th><th>Pokok</th><th>Tenor</th><th>Terbayar</th><th>Sisa</th><th>Status</th></tr></thead><tbody>${db.loans.length?db.loans.slice().reverse().map(x=>{const s=Math.max(0,Number(x.amount)-Number(x.paid||0));return `<tr><td><b>${esc(x.member_name)}</b><small class="table-sub">${new Date(x.created_at).toLocaleDateString('id-ID')}</small></td><td>${rupiah(x.amount)}</td><td>${x.tenor} bln</td><td>${rupiah(x.paid||0)}</td><td>${rupiah(s)}</td><td><span class="status ${s?'warning':'active'}">${s?'Berjalan':'Lunas'}</span></td></tr>`}).join(''):'<tr><td colspan="6" class="table-empty">Belum ada pinjaman.</td></tr>'}</tbody></table></div></section>`}
function payments(){return `${header('PENAGIHAN','Angsuran','Catat pembayaran angsuran dan pantau kewajiban anggota.','<button class="dapin-primary" data-dapin-action="add-payment">＋ Catat Pembayaran</button>')}<section class="dapin-panel"><div class="dapin-table-wrap"><table><thead><tr><th>Tanggal</th><th>Anggota</th><th>Pinjaman</th><th>Nominal</th><th>Metode</th></tr></thead><tbody>${db.payments.length?db.payments.slice().reverse().map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString('id-ID')}</td><td>${esc(x.member_name)}</td><td>${esc(x.loan_label||'-')}</td><td class="money-in">+${rupiah(x.amount)}</td><td>${esc(x.method||'Tunai')}</td></tr>`).join(''):'<tr><td colspan="5" class="table-empty">Belum ada pembayaran angsuran.</td></tr>'}</tbody></table></div></section>`}
function transactions(){const rows=[...db.savings.map(x=>({date:x.created_at,label:'Simpanan '+x.type,member:x.member_name,amount:x.amount,type:'in'})),...db.payments.map(x=>({date:x.created_at,label:'Angsuran',member:x.member_name,amount:x.amount,type:'in'})),...db.loans.map(x=>({date:x.created_at,label:'Pencairan pinjaman',member:x.member_name,amount:x.amount,type:'out'}))].sort((a,b)=>new Date(b.date)-new Date(a.date));return `${header('LEDGER','Transaksi','Buku transaksi DAPIN dari seluruh modul.','<button class="dapin-primary" data-dapin-action="add-transaction">＋ Transaksi Manual</button>')}<section class="dapin-panel"><div class="dapin-table-wrap"><table><thead><tr><th>Tanggal</th><th>Deskripsi</th><th>Anggota</th><th>Debit/Kredit</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td>${new Date(x.date).toLocaleString('id-ID')}</td><td>${esc(x.label)}</td><td>${esc(x.member)}</td><td class="${x.type==='in'?'money-in':'money-out'}">${x.type==='in'?'+':'-'}${rupiah(x.amount)}</td></tr>`).join(''):'<tr><td colspan="4" class="table-empty">Belum ada transaksi.</td></tr>'}</tbody></table></div></section>`}
function reports(){return `${header('PELAPORAN','Laporan','Ringkasan data DAPIN yang siap dicetak atau diekspor.','<button class="dapin-secondary" onclick="window.print()">Cetak Laporan</button>')}<div class="report-grid"><article><span>Jumlah anggota</span><strong>${db.members.length}</strong></article><article><span>Total simpanan</span><strong>${rupiah(totalSavings())}</strong></article><article><span>Total pinjaman</span><strong>${rupiah(db.loans.reduce((a,x)=>a+Number(x.amount||0),0))}</strong></article><article><span>Total angsuran</span><strong>${rupiah(db.payments.reduce((a,x)=>a+Number(x.amount||0),0))}</strong></article></div><section class="dapin-panel report-paper"><div class="report-title"><strong>DAPIN BALONGBENDO</strong><span>Laporan Ringkas</span></div><div class="report-lines"><p><span>Anggota aktif</span><b>${db.members.length}</b></p><p><span>Simpanan tercatat</span><b>${rupiah(totalSavings())}</b></p><p><span>Pinjaman berjalan</span><b>${rupiah(outstanding())}</b></p><p><span>Angsuran masuk</span><b>${rupiah(db.payments.reduce((a,x)=>a+Number(x.amount||0),0))}</b></p></div></section>`}

function memberOptions(){return db.members.map(m=>`<option value="${m.id}">${esc(m.code)} — ${esc(m.name)}</option>`).join('')}
function modal(title,body){return `<div class="dapin-modal-wrap"><div class="dapin-modal"><button class="dapin-close" data-dapin-close>×</button><div class="eyebrow">DAPIN</div><h2>${title}</h2>${body}</div></div>`}
function form(action,fields){return modal(fields.title,`<form data-dapin-form="${action}">${fields.body}<div class="dapin-form-actions"><button type="button" class="dapin-secondary" data-dapin-close>Batal</button><button class="dapin-primary">Simpan</button></div></form>`)}

export function openDapinModal(action){
 if(action==='add-member')return form(action,{title:'Tambah Anggota',body:`<div class="dapin-form-grid"><label>Nomor Anggota<input name="code" required placeholder="DAP-001"></label><label>Nama Lengkap<input name="name" required placeholder="Nama anggota"></label><label>No. HP<input name="phone" placeholder="08xxxxxxxxxx"></label><label>Tanggal Bergabung<input name="joined" type="date" value="${new Date().toISOString().slice(0,10)}"></label></div>`})
 if(action==='add-saving')return form(action,{title:'Catat Simpanan',body:`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${memberOptions()}</select></label><label>Jenis<select name="type"><option>Simpanan Pokok</option><option>Simpanan Wajib</option><option>Simpanan Sukarela</option></select></label><label>Nominal<input name="amount" type="number" min="1" required placeholder="100000"></label><label>Keterangan<input name="note" placeholder="Keterangan transaksi"></label></div>`})
 if(action==='add-loan')return form(action,{title:'Pinjaman Baru',body:`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${memberOptions()}</select></label><label>Pokok Pinjaman<input name="amount" type="number" min="1" required></label><label>Tenor (bulan)<input name="tenor" type="number" min="1" required></label><label>Keterangan<input name="note"></label></div>`})
 if(action==='add-payment')return form(action,{title:'Catat Pembayaran Angsuran',body:`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${memberOptions()}</select></label><label>Nominal<input name="amount" type="number" min="1" required></label><label>Metode<select name="method"><option>Tunai</option><option>Transfer</option><option>FINORA Wallet</option></select></label><label>Keterangan<input name="note"></label></div>`})
 if(action==='add-transaction')return form(action,{title:'Transaksi Manual',body:`<div class="dapin-form-grid"><label>Deskripsi<input name="label" required></label><label>Anggota<input name="member_name" placeholder="Opsional"></label><label>Nominal<input name="amount" type="number" min="1" required></label><label>Arah<select name="direction"><option value="in">Uang Masuk</option><option value="out">Uang Keluar</option></select></label></div>`})
}

export function handleDapinAction(action,formData){
 const now=new Date().toISOString()
 if(action==='add-member'){db.members.push({id:uid(),code:formData.code,name:formData.name,phone:formData.phone,joined:formData.joined});db.view='anggota'}
 if(action==='add-saving'){const m=db.members.find(x=>x.id===formData.member_id);if(!m)throw Error('Pilih anggota.');db.savings.push({id:uid(),member_id:m.id,member_name:m.name,type:formData.type,amount:Number(formData.amount),note:formData.note,created_at:now});db.view='simpanan'}
 if(action==='add-loan'){const m=db.members.find(x=>x.id===formData.member_id);if(!m)throw Error('Pilih anggota.');db.loans.push({id:uid(),member_id:m.id,member_name:m.name,amount:Number(formData.amount),tenor:Number(formData.tenor),paid:0,status:'active',note:formData.note,created_at:now});db.view='pinjaman'}
 if(action==='add-payment'){const m=db.members.find(x=>x.id===formData.member_id);if(!m)throw Error('Pilih anggota.');db.payments.push({id:uid(),member_id:m.id,member_name:m.name,amount:Number(formData.amount),method:formData.method,note:formData.note,created_at:now});db.loans.filter(x=>x.member_id===m.id&&x.status!=='paid').sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).slice(0,1).forEach(x=>{x.paid=Number(x.paid||0)+Number(formData.amount);if(x.paid>=x.amount)x.status='paid'}) ;db.view='angsuran'}
 if(action==='add-transaction'){db.view='transaksi'}
 save(db);return db.view
}

export function setDapinView(v){if(['dashboard','anggota','simpanan','pinjaman','angsuran','transaksi','laporan'].includes(v)){db.view=v;save(db)}}
export function deleteMember(id){db.members=db.members.filter(x=>x.id!==id);save(db);db.view='anggota'}
