const KEY='finora_dapin_v2'
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0))
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const uid=()=>crypto.randomUUID()
const blank={members:[],savings:[],loans:[],payments:[],transactions:[],view:'dashboard'}
const load=()=>{try{return {...blank,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...blank}}}
const save=()=>localStorage.setItem(KEY,JSON.stringify(db))
let db=load()
const isAdmin=()=>document.querySelector('.session-user small')?.textContent?.trim()==='Administrator'
const email=()=>document.querySelector('.session-user strong')?.textContent?.trim()||''
const ownMembers=()=>db.members.filter(m=>m.email===email())
const total=a=>a.reduce((s,x)=>s+Number(x.amount||0),0)
const memberName=id=>db.members.find(m=>m.id===id)?.name||'Anggota'
const activeLoans=a=>a.filter(x=>Number(x.amount||0)>Number(x.paid||0))
const outstanding=a=>total(activeLoans(a).map(x=>({amount:Number(x.amount)-Number(x.paid||0)})))

export function renderDapin(){
 const admin=isAdmin(); let v=db.view||'dashboard'
 const allowed=admin?['dashboard','anggota','simpanan','pinjaman','angsuran','transaksi','laporan']:['dashboard','simpanan','pinjaman','angsuran','transaksi','profil']
 if(!allowed.includes(v))v='dashboard'; db.view=v
 const pages=admin?{dashboard:adminDashboard,anggota:members,simpanan:adminSavings,pinjaman:adminLoans,angsuran:adminPayments,transaksi:adminTransactions,laporan:reports}:{dashboard:memberDashboard,simpanan:memberSavings,pinjaman:memberLoans,angsuran:memberPayments,transaksi:memberTransactions,profil:profile}
 const menu=admin?[['dashboard','⌂','Dashboard'],['anggota','♙','Anggota'],['simpanan','◈','Simpanan'],['pinjaman','▣','Pinjaman'],['angsuran','◷','Angsuran'],['transaksi','↔','Transaksi'],['laporan','▥','Laporan']]:[['dashboard','⌂','Dashboard'],['simpanan','◈','Simpanan Saya'],['pinjaman','▣','Pinjaman Saya'],['angsuran','◷','Angsuran'],['transaksi','↔','Riwayat Transaksi'],['profil','♙','Profil']]
 return `<section class="dapin-app ${admin?'dapin-admin-panel':'dapin-member-panel'}"><aside class="dapin-sidebar"><div class="dapin-brand"><span>D</span><div><strong>DAPIN</strong><small>Balongbendo</small></div></div><div class="dapin-role">${admin?'ADMIN PANEL':'ANGGOTA PANEL'}</div><div class="dapin-menu">${menu.map(([id,i,l])=>`<button class="dapin-nav ${v===id?'active':''}" data-dapin-view="${id}"><b>${i}</b><span>${l}</span></button>`).join('')}</div><div class="dapin-side-foot"><span class="dapin-live">● FINORA SESSION</span><small>${admin?'Akses administrator':'Akses anggota'}</small></div></aside><div class="dapin-main"><div class="dapin-mobile-head"><button data-dapin-toggle>☰</button><strong>DAPIN ${admin?'ADMIN':'ANGGOTA'}</strong></div>${pages[v]?pages[v]():pages.dashboard()}</div></section>`
}
function header(k,t,d,a=''){return `<div class="dapin-page-head"><div><div class="eyebrow">${k}</div><h1>${t}</h1><p>${d}</p></div>${a}</div>`}
function statCard(label,value,meta='',cls=''){return `<article class="dapin-stat ${cls}"><span>${label}</span><strong>${value}</strong><small>${meta}</small></article>`}
function action(title,desc,icon,view,cls=''){return `<button class="dapin-action-card ${cls}" data-dapin-view="${view}"><b>${icon}</b><span><strong>${title}</strong><small>${desc}</small></span><em>›</em></button>`}
function panel(title,body,extra=''){return `<section class="dapin-panel ${extra}"><div class="dapin-panel-head"><div><span>DAPIN</span><h2>${title}</h2></div></div>${body}</section>`}
function toolbar(left,right=''){return `<div class="dapin-toolbar">${left}${right}</div>`}

function adminDashboard(){
 const totalMembers=db.members.length, saving=total(db.savings), loans=total(db.loans), paid=total(db.payments)
 return header('ADMIN COMMAND CENTER','Dashboard Admin','Pusat kendali operasional DAPIN.','<button class="dapin-primary" data-dapin-action="add-member">＋ Anggota Baru</button>')+
 `<div class="dapin-stat-grid dashboard-stats">${statCard('ANGGOTA',totalMembers,'Data terdaftar','purple')}${statCard('TOTAL SIMPANAN',rupiah(saving),'Akumulasi simpanan','green')}${statCard('PIUTANG BERJALAN',rupiah(outstanding(db.loans)),'Sisa pinjaman aktif','orange')}${statCard('ANGSURAN MASUK',rupiah(paid),'Total pembayaran','cyan')}</div>`+
 `<div class="dapin-dashboard-grid"><div>${panel('Pusat Modul',`<div class="dapin-action-grid">${action('Anggota','Data master anggota','♙','anggota','blue')}${action('Simpanan','Pokok, wajib, sukarela','◈','simpanan','green')}${action('Pinjaman','Pengajuan dan kredit','▣','pinjaman','orange')}${action('Angsuran','Jadwal dan pembayaran','◷','angsuran','purple')}${action('Transaksi','Buku kas / ledger','↔','transaksi','cyan')}${action('Laporan','Analitik dan cetak','▥','laporan','pink')}</div>`)}</div><div>${panel('Ringkasan Kas',`<div class="cash-board"><div><span>Total masuk</span><strong>${rupiah(saving+paid)}</strong></div><div><span>Total pinjaman</span><strong>${rupiah(loans)}</strong></div><div><span>Saldo operasional*</span><strong>${rupiah(saving+paid-loans)}</strong></div><small>*Ringkasan internal berdasarkan data DAPIN.</small></div>`)}</div></div>`+
 panel('Aktivitas Terakhir',db.transactions.length?`<div class="dapin-activity">${db.transactions.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,6).map(t=>`<div><span class="activity-dot ${t.direction==='out'?'out':'in'}">${t.direction==='out'?'↑':'↓'}</span><span><strong>${esc(t.label||'Transaksi')}</strong><small>${new Date(t.created_at).toLocaleString('id-ID')}</small></span><b class="${t.direction==='out'?'money-out':'money-in'}">${t.direction==='out'?'-':'+'}${rupiah(t.amount)}</b></div>`).join('')}</div>`:'<div class="dapin-empty">Belum ada aktivitas.</div>')
}
function memberDashboard(){const ms=ownMembers(),ids=new Set(ms.map(m=>m.id)),sv=db.savings.filter(x=>ids.has(x.member_id)),ln=db.loans.filter(x=>ids.has(x.member_id)),pay=db.payments.filter(x=>ids.has(x.member_id));return header('PORTAL ANGGOTA','Dashboard Saya','Ringkasan simpanan, pinjaman, dan angsuran Anda.')+`<div class="dapin-stat-grid">${statCard('SIMPANAN',rupiah(total(sv)),'Saldo tercatat','green')}${statCard('SISA PINJAMAN',rupiah(outstanding(ln)),'Kewajiban berjalan','orange')}${statCard('ANGSURAN',rupiah(total(pay)),'Pembayaran tercatat','purple')}${statCard('STATUS','Aktif','Keanggotaan','cyan')}</div>`+panel('Akses Cepat',`<div class="dapin-action-grid">${action('Simpanan Saya','Riwayat simpanan','◈','simpanan','green')}${action('Pinjaman Saya','Saldo dan tenor','▣','pinjaman','orange')}${action('Angsuran','Pembayaran','◷','angsuran','purple')}${action('Riwayat Transaksi','Aktivitas akun','↔','transaksi','cyan')}</div>`) }

function members(){return header('DATA MASTER','Anggota','Workspace untuk identitas, status, dan pencarian anggota.','<button class="dapin-primary" data-dapin-action="add-member">＋ Tambah Anggota</button>')+`<div class="dapin-stat-grid compact">${statCard('TOTAL',db.members.length,'Semua anggota','blue')}${statCard('AKTIF',db.members.length,'Status aktif','green')}${statCard('DENGAN PINJAMAN',new Set(db.loans.filter(x=>Number(x.amount)>Number(x.paid||0)).map(x=>x.member_id)).size,'Pinjaman berjalan','orange')}</div>`+panel('Data Master Anggota',toolbar(`<input class="dapin-search" placeholder="Cari nama, email, nomor anggota…">`,`<span>${db.members.length} anggota</span>`)+`<div class="dapin-member-list">${db.members.length?db.members.map(m=>`<article class="member-row"><div class="member-avatar">${esc((m.name||'A').charAt(0).toUpperCase())}</div><div class="member-main"><strong>${esc(m.name)}</strong><small>${esc(m.code)} • ${esc(m.email||'-')}</small></div><div class="member-meta"><span>${esc(m.phone||'-')}</span><span class="status active">Aktif</span></div><button class="table-action" data-dapin-action="delete-member" data-id="${m.id}">Hapus</button></article>`).join(''):'<div class="table-empty">Belum ada anggota.</div>'}</div>`,'members-workspace')}

function adminSavings(){const pokok=total(db.savings.filter(x=>x.type==='Simpanan Pokok')), wajib=total(db.savings.filter(x=>x.type==='Simpanan Wajib')), sukarela=total(db.savings.filter(x=>x.type==='Simpanan Sukarela'));return header('FINANCIAL DEPOSITS','Simpanan','Kelola saldo pokok, wajib, sukarela, dan histori setoran.','<button class="dapin-primary" data-dapin-action="add-saving">＋ Catat Simpanan</button>')+`<div class="dapin-deposit-grid"><div><span>POKOK</span><strong>${rupiah(pokok)}</strong></div><div><span>WAJIB</span><strong>${rupiah(wajib)}</strong></div><div><span>SUKARELA</span><strong>${rupiah(sukarela)}</strong></div></div>`+panel('Histori Setoran',tableSavings(db.savings),'savings-workspace')}
function memberSavings(){const ids=new Set(ownMembers().map(m=>m.id));return header('KEUANGAN','Simpanan Saya','Riwayat simpanan akun Anda.')+tableSavings(db.savings.filter(x=>ids.has(x.member_id)))}
function tableSavings(rows){return `<div class="dapin-table-wrap"><table><thead><tr><th>Tanggal</th><th>Anggota</th><th>Jenis</th><th>Nominal</th><th>Keterangan</th></tr></thead><tbody>${rows.length?rows.slice().reverse().map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString('id-ID')}</td><td><b>${esc(x.member_name||memberName(x.member_id))}</b></td><td><span class="type-chip">${esc(x.type)}</span></td><td class="money-in"><strong>+${rupiah(x.amount)}</strong></td><td>${esc(x.note||'-')}</td></tr>`).join(''):'<tr><td colspan="5" class="table-empty">Belum ada data simpanan.</td></tr>'}</tbody></table></div>`}

function adminLoans(){const active=db.loans.filter(x=>Number(x.amount)>Number(x.paid||0));const paid=db.loans.filter(x=>Number(x.amount)<=Number(x.paid||0));return header('CREDIT WORKSPACE','Pinjaman','Kelola pengajuan, plafon, tenor, dan status kredit.','<button class="dapin-primary" data-dapin-action="add-loan">＋ Pinjaman Baru</button>')+`<div class="loan-pipeline"><div><span>DIAJUKAN</span><strong>0</strong></div><div><span>BERJALAN</span><strong>${active.length}</strong></div><div><span>LUNAS</span><strong>${paid.length}</strong></div><div><span>OUTSTANDING</span><strong>${rupiah(outstanding(db.loans))}</strong></div></div>`+panel('Portofolio Pinjaman',tableLoans(db.loans),'loan-workspace')}
function memberLoans(){const ids=new Set(ownMembers().map(m=>m.id));return header('KREDIT','Pinjaman Saya','Lihat pinjaman dan sisa kewajiban Anda.')+tableLoans(db.loans.filter(x=>ids.has(x.member_id)))}
function tableLoans(rows){return `<div class="dapin-table-wrap"><table class="loan-table"><thead><tr><th>Anggota</th><th>Pokok</th><th>Tenor</th><th>Terbayar</th><th>Sisa</th><th>Status</th></tr></thead><tbody>${rows.length?rows.slice().reverse().map(x=>{const s=Math.max(0,Number(x.amount)-Number(x.paid||0));return `<tr><td><b>${esc(x.member_name||memberName(x.member_id))}</b><small class="table-sub">${esc(x.id||'')}</small></td><td>${rupiah(x.amount)}</td><td><span class="tenor-chip">${x.tenor} bln</span></td><td>${rupiah(x.paid)}</td><td><strong>${rupiah(s)}</strong></td><td><span class="status ${s?'warning':'active'}">${s?'Berjalan':'Lunas'}</span></td></tr>`}).join(''):'<tr><td colspan="6" class="table-empty">Belum ada pinjaman.</td></tr>'}</tbody></table></div>`}

function adminPayments(){const due=db.loans.filter(x=>Number(x.amount)>Number(x.paid||0)).length;return header('COLLECTION','Angsuran','Fokus pada pembayaran, jatuh tempo, dan penagihan anggota.','<button class="dapin-primary" data-dapin-action="add-payment">＋ Catat Pembayaran</button>')+`<div class="collection-board"><div><span>PINJAMAN BERJALAN</span><strong>${due}</strong></div><div><span>PEMBAYARAN TERKUMPUL</span><strong>${rupiah(total(db.payments))}</strong></div><div><span>STATUS</span><strong>${due?'Perlu monitoring':'Stabil'}</strong></div></div>`+panel('Daftar Pembayaran',tablePayments(db.payments),'payments-workspace')}
function memberPayments(){const ids=new Set(ownMembers().map(m=>m.id));return header('PENAGIHAN','Angsuran Saya','Riwayat pembayaran angsuran Anda.')+tablePayments(db.payments.filter(x=>ids.has(x.member_id)))}
function tablePayments(rows){return `<div class="dapin-payment-list">${rows.length?rows.slice().reverse().map(x=>`<article><div class="payment-icon">✓</div><div><strong>${esc(x.member_name||memberName(x.member_id))}</strong><small>${new Date(x.created_at).toLocaleDateString('id-ID')} • ${esc(x.method||'Tunai')}</small></div><b class="money-in">+${rupiah(x.amount)}</b></article>`).join(''):'<div class="table-empty">Belum ada pembayaran.</div>'}</div>`}

function adminTransactions(){const fallback=[...db.savings.map(x=>({created_at:x.created_at,label:'Simpanan '+x.type,member_id:x.member_id,amount:x.amount,direction:'in'})),...db.payments.map(x=>({created_at:x.created_at,label:'Angsuran',member_id:x.member_id,amount:x.amount,direction:'in'})),...db.loans.map(x=>({created_at:x.created_at,label:'Pencairan pinjaman',member_id:x.member_id,amount:x.amount,direction:'out'}))];const rows=db.transactions.length?db.transactions:fallback;const incoming=rows.filter(x=>x.direction!=='out').reduce((s,x)=>s+Number(x.amount||0),0),outgoing=rows.filter(x=>x.direction==='out').reduce((s,x)=>s+Number(x.amount||0),0);return header('CASH LEDGER','Transaksi','Buku kas organisasi: uang masuk, uang keluar, dan histori.','<button class="dapin-primary" data-dapin-action="add-transaction">＋ Transaksi Manual</button>')+`<div class="ledger-summary"><div><span>MASUK</span><strong>${rupiah(incoming)}</strong></div><div><span>KELUAR</span><strong>${rupiah(outgoing)}</strong></div><div><span>NET</span><strong>${rupiah(incoming-outgoing)}</strong></div></div>`+panel('Buku Kas',transactionTable(rows),'ledger-workspace')}
function memberTransactions(){const ids=new Set(ownMembers().map(m=>m.id));return header('LEDGER','Riwayat Transaksi','Aktivitas keuangan akun Anda.')+transactionTable(db.transactions.filter(x=>ids.has(x.member_id)))}
function transactionTable(rows){return `<div class="dapin-ledger-wrap"><div class="ledger-head"><span>WAKTU</span><span>DESKRIPSI</span><span>ANGGOTA</span><span>NOMINAL</span></div>${rows.length?rows.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(x=>`<div class="ledger-row"><span>${new Date(x.created_at).toLocaleString('id-ID')}</span><span><b>${esc(x.label||x.description||'Transaksi')}</b></span><span>${esc(x.member_name||memberName(x.member_id))}</span><strong class="${x.direction==='out'?'money-out':'money-in'}">${x.direction==='out'?'-':'+'}${rupiah(x.amount)}</strong></div>`).join(''):'<div class="table-empty">Belum ada transaksi.</div>'}</div>`}

function reports(){const saving=total(db.savings),loan=total(db.loans),payment=total(db.payments);return header('REPORTING CENTER','Laporan','Workspace laporan operasional dan keuangan DAPIN.','<button class="dapin-primary" onclick="window.print()">Cetak Laporan</button>')+`<div class="report-summary-grid">${statCard('ANGGOTA',db.members.length,'Data master','blue')}${statCard('SIMPANAN',rupiah(saving),'Akumulasi','green')}${statCard('PINJAMAN',rupiah(loan),'Pokok tercatat','orange')}${statCard('ANGSURAN',rupiah(payment),'Pembayaran','purple')}</div>`+`<div class="report-sheet"><div class="report-sheet-head"><div><span>DAPIN BALONGBENDO</span><h2>Laporan Keuangan Operasional</h2><small>Dibuat ${new Date().toLocaleString('id-ID')}</small></div><b>FINORA</b></div><div class="report-lines"><p><span>Total simpanan</span><strong>${rupiah(saving)}</strong></p><p><span>Total pokok pinjaman</span><strong>${rupiah(loan)}</strong></p><p><span>Total angsuran masuk</span><strong>${rupiah(payment)}</strong></p><p><span>Outstanding pinjaman</span><strong>${rupiah(outstanding(db.loans))}</strong></p></div></div>`}
function profile(){return header('AKUN','Profil Saya','Informasi akun anggota yang sedang login.')+panel('Informasi Akun',`<div class="dapin-profile"><strong>${esc(email())}</strong><span>Anggota DAPIN</span><span>Status: Aktif</span></div>`)}

function options(){return db.members.map(m=>`<option value="${m.id}">${esc(m.code)} — ${esc(m.name)}</option>`).join('')}
function modal(title,body){return `<div class="dapin-modal-wrap"><div class="dapin-modal"><button class="dapin-close" data-dapin-close>×</button><div class="eyebrow">DAPIN ADMIN</div><h2>${title}</h2>${body}</div></div>`}
function form(action,title,body){return modal(title,`<form data-dapin-form="${action}">${body}<div class="dapin-form-actions"><button type="button" class="dapin-secondary" data-dapin-close>Batal</button><button class="dapin-primary">Simpan</button></div></form>`)}
export function openDapinModal(action){if(!isAdmin())return null;if(action==='add-member')return form(action,'Tambah Anggota',`<div class="dapin-form-grid"><label>No. Anggota<input name="code" required placeholder="DAP-001"></label><label>Nama<input name="name" required></label><label>Email Anggota<input name="email" type="email" required></label><label>No. HP<input name="phone"></label></div>`);if(action==='add-saving')return form(action,'Catat Simpanan',`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${options()}</select></label><label>Jenis<select name="type"><option>Simpanan Pokok</option><option>Simpanan Wajib</option><option>Simpanan Sukarela</option></select></label><label>Nominal<input name="amount" type="number" min="1" required></label><label>Keterangan<input name="note"></label></div>`);if(action==='add-loan')return form(action,'Pinjaman Baru',`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${options()}</select></label><label>Pokok<input name="amount" type="number" min="1" required></label><label>Tenor (bulan)<input name="tenor" type="number" min="1" required></label></div>`);if(action==='add-payment')return form(action,'Catat Angsuran',`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${options()}</select></label><label>Nominal<input name="amount" type="number" min="1" required></label><label>Metode<select name="method"><option>Tunai</option><option>Transfer</option><option>FINORA Wallet</option></select></label></div>`);if(action==='add-transaction')return form(action,'Transaksi Manual',`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${options()}</select></label><label>Deskripsi<input name="label" required></label><label>Nominal<input name="amount" type="number" min="1" required></label><label>Arah<select name="direction"><option value="in">Masuk</option><option value="out">Keluar</option></select></label></div>`);return null}
export function handleDapinAction(action,fd){if(!isAdmin())throw Error('AKSES_DITOLAK');const now=new Date().toISOString();if(action==='add-member')db.members.push({id:uid(),code:fd.code,name:fd.name,email:fd.email,phone:fd.phone,created_at:now});else if(action==='add-saving'){const m=db.members.find(x=>x.id===fd.member_id);db.savings.push({id:uid(),member_id:fd.member_id,member_name:m?.name,amount:Number(fd.amount),type:fd.type,note:fd.note,created_at:now});}else if(action==='add-loan'){const m=db.members.find(x=>x.id===fd.member_id);db.loans.push({id:uid(),member_id:fd.member_id,member_name:m?.name,amount:Number(fd.amount),tenor:Number(fd.tenor),paid:0,status:'active',created_at:now});}else if(action==='add-payment'){const m=db.members.find(x=>x.id===fd.member_id);db.payments.push({id:uid(),member_id:fd.member_id,member_name:m?.name,amount:Number(fd.amount),method:fd.method,created_at:now});const loan=db.loans.find(x=>x.member_id===fd.member_id&&Number(x.amount)>Number(x.paid||0));if(loan){loan.paid=Number(loan.paid||0)+Number(fd.amount);if(loan.paid>=loan.amount)loan.status='paid'}}else if(action==='add-transaction')db.transactions.push({id:uid(),member_id:fd.member_id,label:fd.label,amount:Number(fd.amount),direction:fd.direction,created_at:now});save()}
export function setDapinView(v){db.view=v;save()}
export function deleteMember(id){if(!isAdmin())throw Error('AKSES_DITOLAK');db.members=db.members.filter(x=>x.id!==id);save();db.view='anggota'}
