const KEY='finora_dapin_v2'
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0))
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const uid=()=>crypto.randomUUID()
const blank={members:[],savings:[],loans:[],payments:[],transactions:[],view:'dashboard'}
const load=()=>{try{return {...blank,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...blank}}}
const save=()=>localStorage.setItem(KEY,JSON.stringify(db))
let db=load()
const isAdmin=()=>document.querySelector('.session-user small')?.textContent?.trim()==='Administrator'
const email=()=>document.querySelector('.session-user strong')?.textContent?.trim()||''
const ownMembers=()=>db.members.filter(m=>m.email===email())
const total=a=>a.reduce((s,x)=>s+Number(x.amount||0),0)
const memberName=id=>db.members.find(m=>m.id===id)?.name||'Anggota'
const activeLoans=a=>a.filter(x=>Number(x.amount||0)>Number(x.paid||0))
const outstanding=a=>total(activeLoans(a).map(x=>({amount:Number(x.amount)-Number(x.paid||0)})))

export function renderDapin(){
 const admin=isAdmin(); let v=db.view||'dashboard'
 const allowed=admin?['dashboard','anggota','simpanan','pinjaman','angsuran','transaksi','laporan']:['dashboard','simpanan','pinjaman','angsuran','transaksi','profil']
 if(!allowed.includes(v))v='dashboard'; db.view=v
 const pages=admin?{dashboard:adminDashboard,anggota:members,simpanan:adminSavings,pinjaman:adminLoans,angsuran:adminPayments,transaksi:adminTransactions,laporan:reports}:{dashboard:memberDashboard,simpanan:memberSavings,pinjaman:memberLoans,angsuran:memberPayments,transaksi:memberTransactions,profil:profile}
 const menu=admin?[['dashboard','⌂','Dashboard'],['anggota','♙','Anggota'],['simpanan','◈','Simpanan'],['pinjaman','▣','Pinjaman'],['angsuran','◷','Angsuran'],['transaksi','↔','Transaksi'],['laporan','▥','Laporan']]:[['dashboard','⌂','Dashboard'],['simpanan','◈','Simpanan Saya'],['pinjaman','▣','Pinjaman Saya'],['angsuran','◷','Angsuran'],['transaksi','↔','Riwayat Transaksi'],['profil','♙','Profil']]
 return `<section class="dapin-app ${admin?'dapin-admin-panel':'dapin-member-panel'}"><aside class="dapin-sidebar"><div class="dapin-brand"><span>D</span><div><strong>DAPIN</strong><small>Balongbendo</small></div></div><div class="dapin-role">${admin?'ADMIN PANEL':'ANGGOTA PANEL'}</div><div class="dapin-menu">${menu.map(([id,i,l])=>`<button class="dapin-nav ${v===id?'active':''}" data-dapin-view="${id}"><b>${i}</b><span>${l}</span></button>`).join('')}</div><div class="dapin-side-foot"><span class="dapin-live">● FINORA SESSION</span><small>${admin?'Akses administrator':'Akses anggota'}</small></div></aside><div class="dapin-main"><div class="dapin-mobile-head"><button data-dapin-toggle>☰</button><strong>DAPIN ${admin?'ADMIN':'ANGGOTA'}</strong></div>${pages[v]?pages[v]():pages.dashboard()}</div></section>`
}
function header(k,t,d,a=''){return `<div class="dapin-page-head"><div><div class="eyebrow">${k}</div><h1>${t}</h1><p>${d}</p></div>${a}</div>`}
function kpis(items){return `<div class="dapin-kpis">${items.map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]||''}</small></article>`).join('')}</div>`}
function panel(title,body){return `<section class="dapin-panel"><div class="dapin-panel-head"><div><span>DAPIN</span><h2>${title}</h2></div></div>${body}</section>`}
function adminDashboard(){return header('ADMINISTRASI','Dashboard Admin','Kontrol operasional simpan pinjam DAPIN.','<button class="dapin-primary" data-dapin-action="add-member">＋ Anggota Baru</button>')+kpis([['Total Anggota',db.members.length,'Terdaftar'],['Total Simpanan',rupiah(total(db.savings)),'Seluruh anggota'],['Piutang Berjalan',rupiah(outstanding(db.loans)),'Pinjaman aktif'],['Angsuran Masuk',rupiah(total(db.payments)),'Total tercatat']])+panel('Modul Admin',`<div class="dapin-modules">${[['anggota','♙','Anggota','Kelola data anggota'],['simpanan','◈','Simpanan','Catat dan audit simpanan'],['pinjaman','▣','Pinjaman','Kelola pengajuan dan pencairan'],['angsuran','◷','Angsuran','Catat pembayaran'],['transaksi','↔','Transaksi','Ledger organisasi'],['laporan','▥','Laporan','Laporan operasional']].map(x=>`<button data-dapin-view="${x[0]}"><b>${x[1]}</b><span><strong>${x[2]}</strong><small>${x[3]}</small></span><em>›</em></button>`).join('')}</div>`)}
function memberDashboard(){const ms=ownMembers(),ids=new Set(ms.map(m=>m.id)),sv=db.savings.filter(x=>ids.has(x.member_id)),ln=db.loans.filter(x=>ids.has(x.member_id)),pay=db.payments.filter(x=>ids.has(x.member_id));return header('PORTAL ANGGOTA','Dashboard Saya','Ringkasan simpanan, pinjaman, dan angsuran Anda.')+kpis([['Simpanan',rupiah(total(sv)),'Saldo tercatat'],['Pinjaman Aktif',rupiah(outstanding(ln)),'Sisa pokok'],['Angsuran',rupiah(total(pay)),'Pembayaran tercatat'],['Status','Aktif','Keanggotaan']])+panel('Akses Cepat',`<div class="dapin-modules">${[['simpanan','◈','Simpanan Saya','Lihat riwayat simpanan'],['pinjaman','▣','Pinjaman Saya','Lihat saldo pinjaman'],['angsuran','◷','Angsuran','Lihat pembayaran'],['transaksi','↔','Riwayat Transaksi','Lihat aktivitas akun']].map(x=>`<button data-dapin-view="${x[0]}"><b>${x[1]}</b><span><strong>${x[2]}</strong><small>${x[3]}</small></span><em>›</em></button>`).join('')}</div>`)}
function members(){return header('DATA MASTER','Anggota','Kelola identitas dan status seluruh anggota.','<button class="dapin-primary" data-dapin-action="add-member">＋ Tambah Anggota</button>')+panel('Daftar Anggota',`<div class="dapin-table-wrap"><table><thead><tr><th>No.</th><th>Nama</th><th>Email</th><th>HP</th><th>Status</th><th></th></tr></thead><tbody>${db.members.length?db.members.map(m=>`<tr><td>${esc(m.code)}</td><td><b>${esc(m.name)}</b></td><td>${esc(m.email||'-')}</td><td>${esc(m.phone||'-')}</td><td><span class="status active">Aktif</span></td><td><button class="table-action" data-dapin-action="delete-member" data-id="${m.id}">Hapus</button></td></tr>`).join(''):'<tr><td colspan="6" class="table-empty">Belum ada anggota.</td></tr>'}</tbody></table></div>`)}
function adminSavings(){return header('KEUANGAN','Simpanan','Kelola seluruh simpanan anggota.','<button class="dapin-primary" data-dapin-action="add-saving">＋ Catat Simpanan</button>')+tableSavings(db.savings)}
function memberSavings(){const ids=new Set(ownMembers().map(m=>m.id));return header('KEUANGAN','Simpanan Saya','Riwayat simpanan akun Anda.')+tableSavings(db.savings.filter(x=>ids.has(x.member_id)))}
function tableSavings(rows){return panel('Riwayat Simpanan',`<div class="dapin-table-wrap"><table><thead><tr><th>Tanggal</th><th>Anggota</th><th>Jenis</th><th>Nominal</th><th>Keterangan</th></tr></thead><tbody>${rows.length?rows.slice().reverse().map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString('id-ID')}</td><td>${esc(x.member_name||memberName(x.member_id))}</td><td>${esc(x.type)}</td><td class="money-in">+${rupiah(x.amount)}</td><td>${esc(x.note||'-')}</td></tr>`).join(''):'<tr><td colspan="5" class="table-empty">Belum ada data.</td></tr>'}</tbody></table></div>`)}
function adminLoans(){return header('KREDIT','Pinjaman','Kelola pengajuan, pencairan, dan saldo pinjaman.','<button class="dapin-primary" data-dapin-action="add-loan">＋ Pinjaman Baru</button>')+tableLoans(db.loans)}
function memberLoans(){const ids=new Set(ownMembers().map(m=>m.id));return header('KREDIT','Pinjaman Saya','Lihat pinjaman dan sisa kewajiban Anda.')+tableLoans(db.loans.filter(x=>ids.has(x.member_id)))}
function tableLoans(rows){return panel('Daftar Pinjaman',`<div class="dapin-table-wrap"><table><thead><tr><th>Anggota</th><th>Pokok</th><th>Tenor</th><th>Terbayar</th><th>Sisa</th><th>Status</th></tr></thead><tbody>${rows.length?rows.slice().reverse().map(x=>{const s=Math.max(0,Number(x.amount)-Number(x.paid||0));return `<tr><td>${esc(x.member_name||memberName(x.member_id))}</td><td>${rupiah(x.amount)}</td><td>${x.tenor} bln</td><td>${rupiah(x.paid)}</td><td>${rupiah(s)}</td><td><span class="status ${s?'warning':'active'}">${s?'Berjalan':'Lunas'}</span></td></tr>`}).join(''):'<tr><td colspan="6" class="table-empty">Belum ada pinjaman.</td></tr>'}</tbody></table></div>`)}
function adminPayments(){return header('PENAGIHAN','Angsuran','Kelola pembayaran seluruh anggota.','<button class="dapin-primary" data-dapin-action="add-payment">＋ Catat Pembayaran</button>')+tablePayments(db.payments)}
function memberPayments(){const ids=new Set(ownMembers().map(m=>m.id));return header('PENAGIHAN','Angsuran Saya','Riwayat pembayaran angsuran Anda.')+tablePayments(db.payments.filter(x=>ids.has(x.member_id)))}
function tablePayments(rows){return panel('Pembayaran',`<div class="dapin-table-wrap"><table><thead><tr><th>Tanggal</th><th>Anggota</th><th>Nominal</th><th>Metode</th></tr></thead><tbody>${rows.length?rows.slice().reverse().map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString('id-ID')}</td><td>${esc(x.member_name||memberName(x.member_id))}</td><td class="money-in">+${rupiah(x.amount)}</td><td>${esc(x.method||'Tunai')}</td></tr>`).join(''):'<tr><td colspan="4" class="table-empty">Belum ada pembayaran.</td></tr>'}</tbody></table></div>`)}
function adminTransactions(){const fallback=[...db.savings.map(x=>({created_at:x.created_at,label:'Simpanan '+x.type,member_id:x.member_id,amount:x.amount,direction:'in'})),...db.payments.map(x=>({created_at:x.created_at,label:'Angsuran',member_id:x.member_id,amount:x.amount,direction:'in'})),...db.loans.map(x=>({created_at:x.created_at,label:'Pencairan pinjaman',member_id:x.member_id,amount:x.amount,direction:'out'}))];return header('LEDGER','Transaksi','Buku transaksi organisasi.','<button class="dapin-primary" data-dapin-action="add-transaction">＋ Transaksi Manual</button>')+transactionTable(db.transactions.length?db.transactions:fallback)}
function memberTransactions(){const ids=new Set(ownMembers().map(m=>m.id));return header('LEDGER','Riwayat Transaksi','Aktivitas keuangan akun Anda.')+transactionTable(db.transactions.filter(x=>ids.has(x.member_id)))}
function transactionTable(rows){return panel('Ledger',`<div class="dapin-table-wrap"><table><thead><tr><th>Waktu</th><th>Deskripsi</th><th>Anggota</th><th>Nominal</th></tr></thead><tbody>${rows.length?rows.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('id-ID')}</td><td>${esc(x.label||x.description||'Transaksi')}</td><td>${esc(x.member_name||memberName(x.member_id))}</td><td class="${x.direction==='out'?'money-out':'money-in'}">${x.direction==='out'?'-':'+'}${rupiah(x.amount)}</td></tr>`).join(''):'<tr><td colspan="4" class="table-empty">Belum ada transaksi.</td></tr>'}</tbody></table></div>`)}
function reports(){return header('PELAPORAN','Laporan Keuangan','Ringkasan operasional seluruh DAPIN.','<button class="dapin-secondary" onclick="window.print()">Cetak</button>')+kpis([['Anggota',db.members.length],['Simpanan',rupiah(total(db.savings))],['Pinjaman',rupiah(total(db.loans))],['Angsuran',rupiah(total(db.payments))]])+panel('Ringkasan','<p>Laporan bersumber dari data DAPIN yang tersimpan pada sesi aplikasi.</p>')}
function profile(){return header('AKUN','Profil Saya','Informasi akun anggota yang sedang login.')+panel('Informasi Akun',`<div class="dapin-profile"><strong>${esc(email())}</strong><span>Anggota DAPIN</span><span>Status: Aktif</span></div>`)}
function options(){return db.members.map(m=>`<option value="${m.id}">${esc(m.code)} — ${esc(m.name)}</option>`).join('')}
function modal(title,body){return `<div class="dapin-modal-wrap"><div class="dapin-modal"><button class="dapin-close" data-dapin-close>×</button><div class="eyebrow">DAPIN ADMIN</div><h2>${title}</h2>${body}</div></div>`}
function form(action,title,body){return modal(title,`<form data-dapin-form="${action}">${body}<div class="dapin-form-actions"><button type="button" class="dapin-secondary" data-dapin-close>Batal</button><button class="dapin-primary">Simpan</button></div></form>`)}
export function openDapinModal(action){if(!isAdmin())return null;if(action==='add-member')return form(action,'Tambah Anggota',`<div class="dapin-form-grid"><label>No. Anggota<input name="code" required placeholder="DAP-001"></label><label>Nama<input name="name" required></label><label>Email Anggota<input name="email" type="email" required></label><label>No. HP<input name="phone"></label></div>`);if(action==='add-saving')return form(action,'Catat Simpanan',`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${options()}</select></label><label>Jenis<select name="type"><option>Simpanan Pokok</option><option>Simpanan Wajib</option><option>Simpanan Sukarela</option></select></label><label>Nominal<input name="amount" type="number" min="1" required></label><label>Keterangan<input name="note"></label></div>`);if(action==='add-loan')return form(action,'Pinjaman Baru',`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${options()}</select></label><label>Pokok<input name="amount" type="number" min="1" required></label><label>Tenor (bulan)<input name="tenor" type="number" min="1" required></label></div>`);if(action==='add-payment')return form(action,'Catat Angsuran',`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${options()}</select></label><label>Nominal<input name="amount" type="number" min="1" required></label><label>Metode<select name="method"><option>Tunai</option><option>Transfer</option><option>FINORA Wallet</option></select></label></div>`);if(action==='add-transaction')return form(action,'Transaksi Manual',`<div class="dapin-form-grid"><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option>${options()}</select></label><label>Deskripsi<input name="label" required></label><label>Nominal<input name="amount" type="number" min="1" required></label><label>Arah<select name="direction"><option value="in">Masuk</option><option value="out">Keluar</option></select></label></div>`);return null}
export function handleDapinAction(action,fd){if(!isAdmin())throw Error('AKSES_DITOLAK');const now=new Date().toISOString();if(action==='add-member')db.members.push({id:uid(),code:fd.code,name:fd.name,email:fd.email,phone:fd.phone,created_at:now});else if(action==='add-saving'){const m=db.members.find(x=>x.id===fd.member_id);db.savings.push({id:uid(),member_id:fd.member_id,member_name:m?.name,amount:Number(fd.amount),type:fd.type,note:fd.note,created_at:now});}else if(action==='add-loan'){const m=db.members.find(x=>x.id===fd.member_id);db.loans.push({id:uid(),member_id:fd.member_id,member_name:m?.name,amount:Number(fd.amount),tenor:Number(fd.tenor),paid:0,status:'active',created_at:now});}else if(action==='add-payment'){const m=db.members.find(x=>x.id===fd.member_id);db.payments.push({id:uid(),member_id:fd.member_id,member_name:m?.name,amount:Number(fd.amount),method:fd.method,created_at:now});const loan=db.loans.find(x=>x.member_id===fd.member_id&&Number(x.amount)>Number(x.paid||0));if(loan){loan.paid=Number(loan.paid||0)+Number(fd.amount);if(loan.paid>=loan.amount)loan.status='paid'}}else if(action==='add-transaction')db.transactions.push({id:uid(),member_id:fd.member_id,label:fd.label,amount:Number(fd.amount),direction:fd.direction,created_at:now});save()}
export function setDapinView(v){db.view=v;save()}
export function deleteMember(id){if(!isAdmin())throw Error('AKSES_DITOLAK');db.members=db.members.filter(x=>x.id!==id);save();db.view='anggota'}
