import './style.css'

const role = 'admin'
let active = role === 'admin' ? 'admin-dashboard' : 'member-dashboard'
const adminMenu=[{section:'ADMIN',items:[['admin-dashboard','Dashboard','⌂'],['members','Anggota','♙'],['deposits','Simpanan','＋'],['loans','Pinjaman','▣'],['installments','Angsuran','◷'],['cash','Kas','◈'],['transactions','Transaksi','↔'],['reports','Laporan','▤']]},{section:'SISTEM',items:[['users','User Management','♙'],['security','Security','◉'],['settings','Pengaturan','⚙']]}]
const memberMenu=[{section:'ANGGOTA',items:[['member-dashboard','Dashboard','⌂'],['my-savings','Simpanan Saya','◇'],['my-loans','Pinjaman Saya','▣'],['my-installments','Angsuran Saya','◷'],['my-transactions','Transaksi Saya','↔'],['apply-loan','Ajukan Pinjaman','＋'],['notifications','Notifikasi','●'],['profile','Profil','♙']]}]
const menu=role==='admin'?adminMenu:memberMenu
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)
const allItems=()=>menu.flatMap(g=>g.items)
const label=id=>allItems().find(x=>x[0]===id)?.[1]||'Dashboard'

function adminDashboard(){return `<div class="page"><div class="hero"><div><div class="eyebrow">FINORA • ADMIN</div><h1>Dashboard Administrator</h1><p>Pusat pengelolaan FINORA dan DAPIN untuk seluruh anggota.</p></div></div><div class="stats"><article class="balance"><span>Saldo Kas</span><strong>${money(28500000)}</strong><small>Saldo operasional</small></article><article><span>Total Anggota</span><strong>248</strong><small>+12 bulan ini</small></article><article><span>Pinjaman Aktif</span><strong>${money(12000000)}</strong><small>34 pinjaman</small></article><article><span>Angsuran Hari Ini</span><strong>${money(1850000)}</strong><small class="warning">7 menunggu</small></article></div><div class="grid2"><section class="panel"><div class="panel-head"><div><div class="eyebrow">DAPIN</div><h2>Operasional</h2></div></div>${[['Simpanan','Rp28.500.000'],['Pinjaman','Rp12.000.000'],['Kas tersedia','Rp9.850.000']].map(x=>`<div class="admin-row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</section><section class="panel"><div class="panel-head"><div><div class="eyebrow">AKTIVITAS</div><h2>Perlu perhatian</h2></div></div>${['7 angsuran menunggu pembayaran','3 pengajuan pinjaman baru','2 anggota belum melengkapi data'].map(x=>`<div class="notice">${x}<span>→</span></div>`).join('')}</section></div></div>`}
function memberDashboard(){return `<div class="page"><div class="hero"><div><div class="eyebrow">FINORA • ANGGOTA</div><h1>Dashboard Saya</h1><p>Kelola dan lihat data keuangan milikmu sendiri.</p></div></div><div class="stats"><article class="balance"><span>Simpanan Saya</span><strong>${money(1250000)}</strong><small>Pokok + wajib + sukarela</small></article><article><span>Pinjaman Berjalan</span><strong>${money(5000000)}</strong><small>Tenor 12 bulan</small></article><article><span>Angsuran Berikutnya</span><strong>${money(450000)}</strong><small>Jatuh tempo 5 Sep</small></article><article><span>Status Anggota</span><strong class="online">Aktif</strong><small>Keanggotaan aktif</small></article></div></div>`}

const adminPages={
 members:{title:'Data Anggota',eyebrow:'MANAJEMEN ANGGOTA',desc:'Daftar seluruh anggota DAPIN beserta status dan informasi keanggotaannya.',action:'＋ Tambah Anggota',columns:['ID','Nama Anggota','No. HP','Simpanan','Status'],rows:[['AG-001','Budi Santoso','0812••••1201','Rp1.250.000','Aktif'],['AG-002','Siti Aminah','0813••••8842','Rp2.100.000','Aktif'],['AG-003','Rudi Hartono','0821••••4420','Rp750.000','Aktif']]},
 deposits:{title:'Simpanan',eyebrow:'DAPIN • SIMPANAN',desc:'Kelola simpanan pokok, wajib, sukarela, dan seluruh pencatatannya.',action:'＋ Catat Simpanan',columns:['Tanggal','Anggota','Jenis','Nominal','Status'],rows:[['26 Agu','Budi Santoso','Wajib','Rp100.000','Berhasil'],['26 Agu','Siti Aminah','Sukarela','Rp250.000','Berhasil'],['25 Agu','Rudi Hartono','Pokok','Rp500.000','Berhasil']]},
 loans:{title:'Pinjaman',eyebrow:'DAPIN • PINJAMAN',desc:'Kelola pengajuan, persetujuan, pinjaman aktif, dan pelunasan anggota.',action:'＋ Pengajuan Baru',columns:['No','Anggota','Pokok','Tenor','Status'],rows:[['PJ-102','Budi Santoso','Rp5.000.000','12 Bulan','Aktif'],['PJ-103','Siti Aminah','Rp3.000.000','10 Bulan','Menunggu'],['PJ-104','Rudi Hartono','Rp2.500.000','8 Bulan','Aktif']]},
 installments:{title:'Angsuran',eyebrow:'DAPIN • ANGSURAN',desc:'Pantau jadwal, tagihan, pembayaran, dan keterlambatan angsuran.',action:'＋ Catat Pembayaran',columns:['Jatuh Tempo','Anggota','Angsuran','Ke','Status'],rows:[['05 Sep','Budi Santoso','Rp450.000','3/12','Menunggu'],['03 Sep','Siti Aminah','Rp350.000','5/10','Lunas'],['01 Sep','Rudi Hartono','Rp325.000','4/8','Menunggu']]},
 cash:{title:'Kas DAPIN',eyebrow:'KEUANGAN • KAS',desc:'Pantau pemasukan, pengeluaran, dan posisi saldo kas organisasi.',action:'＋ Transaksi Kas',columns:['Tanggal','Keterangan','Jenis','Nominal','Saldo'],rows:[['26 Agu','Setoran simpanan','Masuk','Rp350.000','Rp9.850.000'],['25 Agu','Operasional','Keluar','Rp150.000','Rp9.500.000'],['24 Agu','Setoran simpanan','Masuk','Rp600.000','Rp9.650.000']]},
 transactions:{title:'Transaksi',eyebrow:'FINORA • TRANSAKSI',desc:'Riwayat seluruh transaksi keuangan FINORA dan DAPIN.',action:'↗ Transaksi Baru',columns:['Waktu','Referensi','Anggota','Kategori','Nominal'],rows:[['10:42','TRX-9281','Budi Santoso','Simpanan','+Rp100.000'],['09:18','TRX-9280','Siti Aminah','Angsuran','-Rp350.000'],['Kemarin','TRX-9279','Rudi Hartono','Simpanan','+Rp250.000']]},
 reports:{title:'Laporan',eyebrow:'ANALYTICS • LAPORAN',desc:'Ringkasan keuangan dan aktivitas DAPIN berdasarkan periode.',action:'▤ Export Laporan',columns:['Laporan','Periode','Data','Status'],rows:[['Rekap Simpanan','Agustus 2026','248 anggota','Siap'],['Pinjaman Aktif','Agustus 2026','34 pinjaman','Siap'],['Kas Masuk/Keluar','Agustus 2026','Rp9.850.000','Siap']]},
 users:{title:'User Management',eyebrow:'SISTEM • USER MANAGEMENT',desc:'Kelola akun aplikasi dan hak akses berdasarkan role.',action:'＋ Tambah User',columns:['User','Email','Role','Status'],rows:[['Angga','admin@finora.id','Administrator','Aktif'],['Budi Santoso','budi@finora.id','Anggota','Aktif'],['Siti Aminah','siti@finora.id','Anggota','Aktif']]},
 security:{title:'Security',eyebrow:'SISTEM • SECURITY',desc:'Kelola keamanan akun, sesi, autentikasi, dan kontrol akses.',action:'Simpan Security',columns:['Pengaturan','Status','Keterangan'],rows:[['Two-Factor Authentication','Aktif','Disarankan untuk admin'],['Session Timeout','30 menit','Otomatis logout'],['Role Protection','Aktif','Admin / Anggota terpisah']]},
 settings:{title:'Pengaturan',eyebrow:'SISTEM • PENGATURAN',desc:'Konfigurasi identitas, operasional, dan preferensi aplikasi FINORA.',action:'Simpan Pengaturan',columns:['Pengaturan','Nilai','Status'],rows:[['Nama Organisasi','DAPIN Balongbendo','Aktif'],['Mata Uang','IDR / Rupiah','Aktif'],['Mode Sistem','Production','Aktif']]}
}
const memberPages={
 'my-savings':{title:'Simpanan Saya',eyebrow:'ANGGOTA • SIMPANAN',desc:'Saldo dan riwayat simpanan pribadi.'},'my-loans':{title:'Pinjaman Saya',eyebrow:'ANGGOTA • PINJAMAN',desc:'Pinjaman aktif dan riwayat pinjaman pribadi.'},'my-installments':{title:'Angsuran Saya',eyebrow:'ANGGOTA • ANGSURAN',desc:'Jadwal dan riwayat angsuran pribadi.'},'my-transactions':{title:'Transaksi Saya',eyebrow:'ANGGOTA • TRANSAKSI',desc:'Riwayat transaksi rekening pribadi.'},'apply-loan':{title:'Ajukan Pinjaman',eyebrow:'ANGGOTA • PENGAJUAN',desc:'Buat dan pantau pengajuan pinjaman baru.'},notifications:{title:'Notifikasi',eyebrow:'ANGGOTA • NOTIFIKASI',desc:'Informasi pembayaran, angsuran, dan akun.'},profile:{title:'Profil',eyebrow:'ANGGOTA • PROFIL',desc:'Kelola informasi profil pribadi.'}}
function tablePage(p){return `<div class="page"><div class="hero"><div><div class="eyebrow">${p.eyebrow}</div><h1>${p.title}</h1><p>${p.desc}</p></div>${p.action?`<button class="primary" data-action="toast">${p.action}</button>`:''}</div><section class="panel"><div class="panel-head"><div><div class="eyebrow">DATA</div><h2>${p.title}</h2></div><span class="badge">Aktif</span></div><div class="table-wrap"><table><thead><tr>${p.columns.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${p.rows.map(r=>`<tr>${r.map((v,i)=>`<td class="${i===r.length-1?'status-cell':''}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section></div>`}
function memberPage(p){return `<div class="page"><div class="hero"><div><div class="eyebrow">${p.eyebrow}</div><h1>${p.title}</h1><p>${p.desc}</p></div></div><section class="panel placeholder compact"><div class="big-icon">◇</div><h2>${p.title}</h2><p>Halaman anggota terpisah dari area administrator. Data yang ditampilkan hanya milik anggota yang sedang login.</p></section></div>`}
function content(){if(active==='admin-dashboard')return adminDashboard();if(active==='member-dashboard')return memberDashboard();return role==='admin'?tablePage(adminPages[active]):memberPage(memberPages[active])}
function render(){document.querySelector('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="logo"><span class="logo-mark">F</span><div><b>FINORA</b><small>${role==='admin'?'Administrator':'Member Portal'}</small></div></div><div class="profile"><div class="avatar">${role==='admin'?'A':'M'}</div><div><b>${role==='admin'?'Angga':'Anggota'}</b><small>${role==='admin'?'Administrator':'Anggota DAPIN'}</small></div><span class="dot"></span></div><nav>${menu.map(g=>`<div class="nav-group"><div class="section-title">${g.section}</div>${g.items.map(([id,text,icon])=>`<button class="nav-item ${active===id?'active':''}" data-id="${id}"><span class="nav-icon">${icon}</span><span>${text}</span></button>`).join('')}</div>`).join('')}</nav><div class="sidebar-bottom"><div class="status"><span></span> Sistem Online</div></div></aside><main class="main"><header class="topbar"><div><span class="crumb">FINORA</span><span class="slash">/</span><b>${label(active)}</b></div><div class="top-actions"><button class="icon-btn">⌕</button><button class="icon-btn">♧</button><div class="user-mini">${role==='admin'?'A':'M'}</div></div></header>${content()}</main></div>`;document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{active=b.dataset.id;render()});document.querySelectorAll('[data-action="toast"]').forEach(b=>b.onclick=()=>alert('Aksi '+b.textContent.trim()+' siap dihubungkan ke database.'))}
render()
