import './style.css'

const menu=[
 {section:'FINORA',items:[['dashboard','Dashboard','⌂'],['topup','Top Up','＋'],['withdraw','Tarik Dana','↗'],['transactions','Transaksi','↔'],['savings','Tabungan','◇']]},
 {section:'DAPIN',items:[['dapin-dashboard','Dashboard DAPIN','▦'],['members','Anggota','♙'],['deposits','Simpanan','＋'],['loans','Pinjaman','▣'],['installments','Angsuran','◷'],['cash','Kas','◈'],['reports','Laporan','▤']]},
 {section:'SISTEM',items:[['security','Security','◉'],['settings','Pengaturan','⚙']]}
]
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)
let active='dashboard'
function label(id){return menu.flatMap(g=>g.items).find(x=>x[0]===id)?.[1]||'Dashboard'}
function tx(){return [['Top Up','26 Agu 2026, 10:24','+Rp1.500.000','credit'],['Pembayaran','25 Agu 2026, 18:12','-Rp350.000','debit'],['Simpanan DAPIN','25 Agu 2026, 09:40','-Rp250.000','debit'],['Transfer Masuk','24 Agu 2026, 14:21','+Rp750.000','credit']].map(x=>`<div class="tx"><div class="tx-icon">${x[0][0]}</div><div class="tx-info"><b>${x[0]}</b><small>${x[1]}</small></div><strong class="${x[3]}">${x[2]}</strong></div>`).join('')}
function wallet(){return `<div class="page"><div class="hero"><div><div class="eyebrow">FINORA WALLET</div><h1>Selamat datang kembali, Angga.</h1><p>Kelola keuangan, pembayaran, dan aktivitas wallet dari satu tempat.</p></div><div class="hero-actions"><button class="secondary">＋ Top Up</button><button class="primary">↗ Tarik Dana</button></div></div><div class="stats"><article class="balance"><span>Saldo tersedia</span><strong>${money(12500000)}</strong><small>+8,4% dari bulan lalu</small><div class="balance-line"></div></article><article><span>Total Transaksi</span><strong>128</strong><small>↗ 12 transaksi minggu ini</small></article><article><span>Tabungan</span><strong>${money(4750000)}</strong><small>Target 63% tercapai</small></article><article><span>Status</span><strong class="online">Aktif</strong><small>Wallet terlindungi RLS</small></article></div><div class="grid2"><section class="panel"><div class="panel-head"><div><div class="eyebrow">TRANSAKSI</div><h2>Aktivitas terbaru</h2></div><button class="link">Lihat semua →</button></div>${tx()}</section><section class="panel dapin-card"><div class="panel-head"><div><div class="eyebrow">DAPIN</div><h2>Simpan Pinjam</h2></div><span class="badge">Terintegrasi</span></div><div class="dapin-mini"><div><span>Total simpanan</span><b>${money(28500000)}</b></div><div><span>Pinjaman berjalan</span><b>${money(12000000)}</b></div></div><button class="primary wide" data-id="dapin-dashboard">Buka DAPIN →</button></section></div></div>`}
function dapin(){return `<div class="page"><div class="hero dapin-hero"><div><div class="eyebrow">DAPIN • BALONGBENDO</div><h1>Dashboard Simpan Pinjam</h1><p>Kelola anggota, simpanan, pinjaman, angsuran, kas, dan laporan.</p></div><button class="primary">＋ Transaksi Baru</button></div><div class="stats"><article><span>Total Anggota</span><strong>248</strong><small>+12 bulan ini</small></article><article><span>Total Simpanan</span><strong>${money(28500000)}</strong><small>Pokok + wajib + sukarela</small></article><article><span>Pinjaman Berjalan</span><strong>${money(12000000)}</strong><small>34 pinjaman aktif</small></article><article><span>Angsuran Hari Ini</span><strong>${money(1850000)}</strong><small class="warning">7 pembayaran menunggu</small></article></div><div class="grid2"><section class="panel"><div class="panel-head"><div><div class="eyebrow">RINGKASAN</div><h2>Portofolio DAPIN</h2></div></div><div class="progress-wrap">${[['Pinjaman tersalurkan',68],['Angsuran lancar',91],['Target simpanan',74]].map(x=>`<div class="progress-label"><span>${x[0]}</span><b>${x[1]}%</b></div><div class="progress"><i style="width:${x[1]}%"></i></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><div><div class="eyebrow">JATUH TEMPO</div><h2>Angsuran terdekat</h2></div></div>${['Budi Santoso','Siti Aminah','Rizky Pratama'].map((n,i)=>`<div class="due"><div class="avatar small">${n[0]}</div><div><b>${n}</b><small>Angsuran ke-${i+2}</small></div><strong>${money(350000+i*75000)}</strong></div>`).join('')}</section></div></div>`}
function module(){const names={members:['Anggota','Kelola data anggota DAPIN'],deposits:['Simpanan','Kelola simpanan pokok, wajib, dan sukarela'],loans:['Pinjaman','Pengajuan dan pinjaman berjalan'],installments:['Angsuran','Pembayaran dan jadwal angsuran'],cash:['Kas','Pemasukan dan pengeluaran kas'],reports:['Laporan','Laporan keuangan dan aktivitas DAPIN']};const [title,desc]=names[active];return `<div class="page"><div class="hero"><div><div class="eyebrow">DAPIN</div><h1>${title}</h1><p>${desc}.</p></div><button class="primary">＋ Tambah Data</button></div><section class="panel"><div class="placeholder"><div class="big-icon">◇</div><h2>Modul ${title} siap diintegrasikan</h2><p>Preview UI gabungan FINORA + DAPIN. Struktur sidebar dan halaman sudah disiapkan tanpa mengubah production.</p><button class="secondary" data-id="dapin-dashboard">← Kembali ke Dashboard DAPIN</button></div></section></div>`}
function content(){if(active==='dapin-dashboard')return dapin();if(['members','deposits','loans','installments','cash','reports'].includes(active))return module();return wallet()}
function render(){document.querySelector('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="logo"><span class="logo-mark">F</span><div><b>FINORA</b><small>Financial Platform</small></div></div><div class="profile"><div class="avatar">A</div><div><b>Angga</b><small>Administrator</small></div><span class="dot"></span></div><nav>${menu.map(g=>`<div class="nav-group"><div class="section-title">${g.section}</div>${g.items.map(([id,text,icon])=>`<button class="nav-item ${active===id?'active':''}" data-id="${id}"><span class="nav-icon">${icon}</span><span>${text}</span></button>`).join('')}</div>`).join('')}</nav><div class="sidebar-bottom"><div class="status"><span></span> Sistem Online</div><button class="collapse">‹</button></div></aside><main class="main"><header class="topbar"><div><span class="crumb">FINORA</span><span class="slash">/</span><b>${label(active)}</b></div><div class="top-actions"><button class="icon-btn">⌕</button><button class="icon-btn">♧</button><div class="user-mini">A</div></div></header>${content()}</main></div>`;document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{active=b.dataset.id;render()})}
render()
